### ISSUE TITLE
how to get latest version of this?

### ISSUE THREAD

**Issue by techstay** [JulianChow94/Windows-screenFetch#33]
screenfetch on poweshell gallery is still 1.0.2 and not fix the divided by zero error, how to get latest version of it?

**Comment by lucknaumann** [comment]
I just installed [Install-ModuleFromGitHub](https://dfinke.github.io/powershell/2016/11/21/Quickly-Install-PowerShell-Modules-from-GitHub.html) from [here](https://www.powershellgallery.com/packages/InstallModuleFromGitHub/) and then ran `Find-Module windows-screenfetch | Install-ModuleFromGitHub`

Although this threw an error because of something in windows-screenfetch .psm file (I think) it still installed the latest version (1.0.3) & worked when running `screenfetch` from the prompt.

**Comment by techstay** [comment]
Thank you, I will have a try later since PowershellGet met some trouble.

**Comment by lucknaumann** [comment]
You're welcome. =) OK - let me know how it works for you.
Also - you may get this error when running: [issue#25](https://github.com/JulianChow94/Windows-screenFetch/issues/25#issue-444332797).
